/*--------------------------------------------------------------------------------------------------
 * Author:      Dan Cassidy
 * Date:        2015-06-23
 * Assignment:  cView-P4
 * Source File: CViewDataModelExtension.cs
 * Language:    C#
 * Course:      CSCI-C 490, C# Programming, MoWe 08:00
 * Purpose:     Extends the Business, Park, and PublicFacility class generated by the ASP.NET Entity
 *              Framework for this solution.
--------------------------------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cView_P4_DanCassidy
{
    public partial class Business
    {
        /*------------------------------------------------------------------------------------------
         * Name:    this[]
         * Type:    Indexer
         * Purpose: Provides easy access to the properties of the class.
         * Input:   int fiendNum, represents the desired property.
         * Output:  object, contains whichever property was desired, or null if the property was not
         *          found.
        ------------------------------------------------------------------------------------------*/
        public object this[int fieldNum]
        {
            get
            {
                switch ((Global.Enums.BusinessFields)fieldNum)
                {
                    case Global.Enums.BusinessFields.Name:
                        return Name;
                    case Global.Enums.BusinessFields.Type:
                        return Type;
                    case Global.Enums.BusinessFields.StreetAddress:
                        return StreetAddress;
                    case Global.Enums.BusinessFields.City:
                        return City;
                    case Global.Enums.BusinessFields.State:
                        return State;
                    case Global.Enums.BusinessFields.Zip:
                        return Zip;
                    case Global.Enums.BusinessFields.Latitude:
                        return Latitude;
                    case Global.Enums.BusinessFields.Longitude:
                        return Longitude;
                    case Global.Enums.BusinessFields.Phone:
                        return Phone;
                    case Global.Enums.BusinessFields.LicenseNumber:
                        return LicenseNumber;
                    case Global.Enums.BusinessFields.LicenseIssueDate:
                        return LicenseIssueDate;
                    case Global.Enums.BusinessFields.LicenseExpirDate:
                        return LicenseExpirDate;
                    case Global.Enums.BusinessFields.LicenseStatus:
                        return LicenseStatus;
                    case Global.Enums.BusinessFields.CouncilDistrict:
                        return CouncilDistrict;
                    default:
                        return null;
                }
            }
        }

        //public string this[string fieldName]
        //{
            
        //}
    }

    public partial class Park
    {
        /*------------------------------------------------------------------------------------------
         * Name:    this[]
         * Type:    Indexer
         * Purpose: Provides easy access to the properties of the class.
         * Input:   int fiendNum, represents the desired property.
         * Output:  object, contains whichever property was desired, or null if the property was not
         *          found.
        ------------------------------------------------------------------------------------------*/
        public object this[int fieldNum]
        {
            get
            {
                switch ((Global.Enums.ParkFields)fieldNum)
                {
                    case Global.Enums.ParkFields.Name:
                        return Name;
                    case Global.Enums.ParkFields.Type:
                        return Type;
                    case Global.Enums.ParkFields.StreetAddress:
                        return StreetAddress;
                    case Global.Enums.ParkFields.City:
                        return City;
                    case Global.Enums.ParkFields.State:
                        return State;
                    case Global.Enums.ParkFields.Zip:
                        return Zip;
                    case Global.Enums.ParkFields.Latitude:
                        return Latitude;
                    case Global.Enums.ParkFields.Longitude:
                        return Longitude;
                    case Global.Enums.ParkFields.Phone:
                        return Phone;
                    case Global.Enums.ParkFields.FeatureBaseball:
                        return FeatureBaseball;
                    case Global.Enums.ParkFields.FeatureBasketball:
                        return FeatureBasketball;
                    case Global.Enums.ParkFields.FeatureGolf:
                        return FeatureGolf;
                    case Global.Enums.ParkFields.FeatureLargeMPField:
                        return FeatureLargeMPField;
                    case Global.Enums.ParkFields.FeatureTennis:
                        return FeatureTennis;
                    case Global.Enums.ParkFields.FeatureVolleyball:
                        return FeatureVolleyball;
                    default:
                        return null;
                }
            }
        }
    }

    public partial class PublicFacility
    {
        /*------------------------------------------------------------------------------------------
         * Name:    this[]
         * Type:    Indexer
         * Purpose: Provides easy access to the properties of the class.
         * Input:   int fiendNum, represents the desired property.
         * Output:  object, contains whichever property was desired, or null if the property was not
         *          found.
        ------------------------------------------------------------------------------------------*/
        public object this[int fieldNum]
        {
            get
            {
                switch ((Global.Enums.PublicFacilityFields)fieldNum)
                {
                    case Global.Enums.PublicFacilityFields.Name:
                        return Name;
                    case Global.Enums.PublicFacilityFields.Type:
                        return Type;
                    case Global.Enums.PublicFacilityFields.StreetAddress:
                        return StreetAddress;
                    case Global.Enums.PublicFacilityFields.City:
                        return City;
                    case Global.Enums.PublicFacilityFields.State:
                        return State;
                    case Global.Enums.PublicFacilityFields.Zip:
                        return Zip;
                    case Global.Enums.PublicFacilityFields.Latitude:
                        return Latitude;
                    case Global.Enums.PublicFacilityFields.Longitude:
                        return Longitude;
                    case Global.Enums.PublicFacilityFields.Phone:
                        return Phone;
                    default:
                        return null;
                }
            }
        }
    }
}